#!/bin/bash

. /start-common.sh

SPARK_SERVICE_NAME=${SPARK_SERVICE_NAME:-spark-master}

echo "$(hostname -i) ${SPARK_SERVICE_NAME}" >> /etc/hosts
# Run spark-class directly so that when it exits (or crashes), the pod restarts.
/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip ${SPARK_SERVICE_NAME} --port 7077 --webui-port 8080

