#!/bin/bash

. /start-common.sh

SERVICE=${SPARK_SERVICE_NAME:-spark-master}
MEMORY=${SPARK_EXECUTOR_MEMORY:-1G}
UI_PORT=${SPARK_WORKER_UI_PORT:-8081}

if ! getent hosts ${SERVICE}; then
  echo "=== Cannot resolve the DNS entry for ${SERVICE}. Has the service been created yet, and is SkyDNS functional?"
  echo "=== See http://kubernetes.io/v1.1/docs/admin/dns.html for more details on DNS integration."
  echo "=== Sleeping 10s before pod exit."
  sleep 10
  exit 0
fi

echo "Launching spark workers in container for service ${SERVICE} with memory ${MEMORY} and UI at ${UI_PORT}"

# Run spark-class directly so that when it exits (or crashes), the pod restarts.
/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://${SERVICE}:7077 --webui-port ${UI_PORT} --memory ${MEMORY}

